[package]
name = "file_pipeline"
version = "0.1.0"
authors = ["Mahmoud Tolba"]
edition = "2021"

[dependencies]
actix-web = "4.2.1"
env_logger = "0.10.0"
sqlx = { version = "0.6.2", features = [ "postgres" ] }
serde = { version = "1.0.139", features = [ "derive" ] }
dotenv = "0.15.0"
log = "0.4.16"

#### main.rs